<a href="https://colab.research.google.com/github/divyamvashistha23-netizen/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
array = [3,4,5]
array = array*2
print(array)

[3, 4, 5, 3, 4, 5]


In [ ]:
array = np.array([3,4,5])
array = array*2
print(array)

[ 6  8 10]


In [ ]:
array1 = np.array([[['A', 'B', 'C'], ['E', 'F', 'G'], ['H', 'I', 'J']],
                    [['D', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['A', 'H', 'I']]])
print(array1.ndim)
print(array1.shape)
print(array1.size)
print(array1.dtype)
print(array1.itemsize)
print(array1.data)
print(array1[0,1,2])
word = array1[1,0,0]
print(word)

3
(3, 3, 3)
27
<U1
4
G
DIV


In [17]:
import numpy as np
#Slicing
Matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(Matrix[0:2:])
print(Matrix[1:,2:
          ])

[[1 2 3 4]
 [5 6 7 8]]
[[ 7  8]
 [11 12]]


In [21]:
#arithmetic
import numpy as np
array = np.array([1.23, 3.6, 6.7])
print(np.sqrt(array))
print(np.round(array))
radii = np.array([1, 3, 6])

print(np.pi * radii **2)

[1.10905365 1.8973666  2.58843582]
[1. 4. 7.]
[  3.14159265  28.27433388 113.09733553]
