<a href="https://colab.research.google.com/github/divyamvashistha23-netizen/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
array = [3,4,5]
array = array*2
print(array)

[3, 4, 5, 3, 4, 5]


In [ ]:
array = np.array([3,4,5])
array = array*2
print(array)

[ 6  8 10]


In [ ]:
array1 = np.array([[['A', 'B', 'C'], ['E', 'F', 'G'], ['H', 'I', 'J']],
                    [['D', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['A', 'H', 'I']]])
print(array1.ndim)
print(array1.shape)
print(array1.size)
print(array1.dtype)
print(array1.itemsize)
print(array1.data)
print(array1[0,1,2])
word = array1[1,0,0]
print(word)

3
(3, 3, 3)
27
<U1
4
G
DIV


In [ ]:
import numpy as np
#Slicing
Matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(Matrix[0:2:])
print(Matrix[1:,2:
          ])

[[1 2 3 4]
 [5 6 7 8]]
[[ 7  8]
 [11 12]]


In [ ]:
#arithmetic
import numpy as np
array = np.array([1.23, 3.6, 6.7])
print(np.sqrt(array))
print(np.round(array))
radii = np.array([1, 3, 6])

print(np.pi * radii **2)
# can use comparision operators, +-/\ , etc

[1.10905365 1.8973666  2.58843582]
[1. 4. 7.]
[  3.14159265  28.27433388 113.09733553]


In [1]:
#broadcasting
import numpy as np

array1 = np.array([ [1,2,3,4]])
array2 = np.array([[1], [2], [3], [4]])
print(array1.shape)
print(array2.shape)
array3 = np.array(array1*array2)
print(array3 )

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [6]:
#aggregate functions
import numpy as np
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.median(array))
print(np.percentile(array, 25))
print(np.sum(array, axis=1))

55
5.5
2.8722813232690143
8.25
1
10
0
9
5.5
3.25
[15 40]


In [14]:
#filtering
import numpy as np
ages = np.array([[21,17,19,20,16,30,18,65],
                [39,22,15,99,18,20,21,12]])
teenagers = ages[ages<18]
adults = ages[(ages>=18) | (ages<=65)]


print(teenagers)
print(adults)
Adults = np.where(ages>=18, ages, 0)
print(Adults)

[17 16 15 12]
[21 17 19 20 16 30 18 65 39 22 15 99 18 20 21 12]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 20 21  0]]


In [51]:
#random number
import numpy as np
rng = np.random.default_rng()
print(rng.integers(1, 7, (3,2)))
print(rng.integers(low =-100, high = -67, size= (3,2)))
print(np.random.uniform(-1,1,(3,2)))
age = np.array([21,17,19,20,16,30,18,65])
rng.shuffle(age)
print(age)


[[1 5]
 [4 6]
 [3 6]]
[[-89 -69]
 [-87 -88]
 [-82 -95]]
[[-0.00836046 -0.66404392]
 [ 0.35312319  0.3156864 ]
 [-0.47332909 -0.17299988]]
[20 21 19 65 30 18 16 17]
